### ISSUE TITLE
Streams play but stop after 30-60 seconds

### ISSUE THREAD

**Issue by remus77** [beardypig/plugin.video.blxdtvcatchup#3]
Following the problem last week, the add-on appears to work, it opens streams but they only play for 30-60 seconds then stop.
Tried on multiple devices on multiple environments with the same result.
No error is logged.

**Comment by remus77** [comment]
Hi Beardypig.  Your fix applied just now, has this exact same problem.  The streams play for around 30 seconds then stop again....

**Comment by beardypig** [comment]
@remus77 can you check which version you are running?

**Comment by remus77** [comment]
2.1.0

**Comment by beardypig** [comment]
OK. Confirmed... I'll work on a fix for that :(

**Comment by beardypig** [comment]
@remus77 which channels do you have the problem on? Seems like the BBC channels do not have the issue, but ITV etc. do.

**Comment by remus77** [comment]
It happened to me on BBC1 BBC2 and ITV....
Will try some more now

**Comment by beardypig** [comment]
Which version of Kodi are you running? I've been testing on 17.5.

**Comment by remus77** [comment]
I'm getting the issue on every channel I try.  Testing right now on Kodi 16.2 but have tried on various versions of both Kodi and SPMC.   Will try on 17.5 in a moment...

**Comment by remus77** [comment]
Weird.  On ITV and Ch4, still drops out on 17.5 but as you say BBC1 and BBC2 seem to run for at least a few minutes. Going to leave them running a while...

**Comment by remus77** [comment]
To confirm.  Had the same channel running now for 20 minutes.  This is on Kodi 17.5 but the same channel on 16.2 stopped in under a minute.  Likewise, the ITV channel on Kodi 17.5 ran for under 40 seconds 20 consecutive times.  However, I've just tried ITV and it's now still running after 90 seconds...

**Comment by beardypig** [comment]
@remus77 I just deployed `2.1.1` which should resolve the issues with the streams stopping after a while - I had ITV playing for 10 minutes with no problems.

**Comment by beardypig** [comment]
Re-open this issue if you still have issues 🐞
